### ISSUE TITLE
Looks like browserify is an implicit dependency

### ISSUE THREAD

**Issue by DjebbZ** [cyclejs/cycle-time-travel#26]
Browserify appears in the `scripts` section of package.json but not in `devDependencies`.

**Comment by Widdershin** [comment]
Ah true, I'll add that as a dependency, cheers.

**Comment by DjebbZ** [comment]
Better like this, right ? :)

**Comment by Widdershin** [comment]
Definitely, thanks for making an issue :)

Anyone should be able to clone the repo, `npm install` and go.
